# Project information
site_name: Medal of Honor Reborn
site_description: Medal of Honor Reborn Community Patch
site_author: Michał 'Razo[R]apiD' Knieć
site_url: https://mohreborn.github.io/mohreborn-docs/

# Repository
repo_name: mohreborn/mohreborn-docs
repo_url: https://github.com/mohreborn/mohreborn-docs
edit_uri: ''

# Copyright
copyright: Copyright &copy; 2020 MoH Reborn Team

# Page tree
nav:
  - 'Home': index.md
  - 'Getting started':
      - 'Start': getting-started/index.md
      - 'Players': getting-started/players.md
      - 'Server owners': getting-started/server-owners.md
      - 'Manual patching': getting-started/manual-patching.md
      - 'Other': getting-started/other.md
  - 'Downloads': downloads.md
  - 'Documentation':
      - 'Features Overview': features/features-overview.md
      - 'For Players':
          - 'Player voting': features/player/player-voting.md
      - 'For Server Admins':
          - 'Admin accounts and permissions': features/server-admin/accounts-and-permissions.md
          - 'Banning and kicking players': features/server-admin/banning-kicking-players.md
          - 'Chat management': features/server-admin/chat-management.md
          - 'Protected player names': features/server-admin/protected-player-names.md
          - 'Anti Wallhack': features/server-admin/anti-wallhack.md
          - 'Anti NoRecoil': features/server-admin/anti-norecoil.md
          - 'Anti STWH': features/server-admin/anti-stwh.md
          - 'High Ping Autokick': features/server-admin/high-ping-autokick.md
          - 'Connections Limiter': features/server-admin/connections-limiter.md
          - 'Anti Packet Flood': features/server-admin/anti-packet-flood.md
          - 'Stufftext Bypass Detection': features/server-admin/stufftext-bypass-detection.md
          - 'Player voting': features/server-admin/player-voting.md
          - 'Automatic updates': features/server-admin/automatic-updates.md
      - 'For Modders':
          - 'Extended scripting': features/modder/extended-scripting.md
          - 'Event system': features/modder/event-system.md
  - 'Resources': resources.md
  - 'About': about.md

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: en
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
#  palette:
#    primary: brown
#    accent: deep orange
  favicon: assets/images/favicon.png
  icon:
    logo: fontawesome/solid/medal
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top

extra_css:
  - styles/extra.css

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mohreborn
    - icon: fontawesome/brands/discord
      link: https://discord.gg/QYNNkCdHBK

# Extensions
markdown_extensions:
  - meta
  - admonition
  - attr_list
  - md_in_html
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
